<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="EventHub.BuildingBlocks" />
    <PackageReference Include="EventHub.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

</Project>